
server:
    interface: 127.0.0.1@5335
    port: 5335
    do-ip6: no

    val-log-level: 1

    unwanted-reply-threshold: 10000000

    harden-below-nxdomain: yes
    harden-large-queries: yes
    harden-short-bufsize: yes

    qname-minimisation: no

    prefetch: yes
    prefetch-key: yes

    serve-expired: yes
    serve-expired-ttl: 604800
    serve-expired-client-timeout: 100

    client-subnet-always-forward: yes

    infra-host-ttl: 3600

    extended-statistics: yes

    aggressive-nsec: yes

    hide-identity: yes
    hide-version: yes

    msg-cache-size: 128m
    rrset-cache-size: 256m
    cache-min-ttl: 300
    neg-cache-size: 4m

    num-threads: 2

    so-rcvbuf: 4m
    so-sndbuf: 4m

    num-queries-per-thread: 2048

    ratelimit: 1000

    access-control: 127.0.0.0/8 allow
    access-control: 0.0.0.0/0 refuse
{{CN_WG_INTERFACE}}

    logfile: "/var/log/dns-stack/unbound.log"

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-port: 8953
    server-key-file: "/etc/unbound/dns-stack_server.key"
    server-cert-file: "/etc/unbound/dns-stack_server.pem"
    control-key-file: "/etc/unbound/dns-stack_control.key"
    control-cert-file: "/etc/unbound/dns-stack_control.pem"
