package ecszone

import (
	"net/netip"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dns-stack/dns-stack/internal/ipset"
)

func addr(t *testing.T, text string) uint32 {
	t.Helper()
	value := netip.MustParseAddr(text).As4()
	return uint32(value[0])<<24 | uint32(value[1])<<16 | uint32(value[2])<<8 | uint32(value[3])
}

func row(t *testing.T, lo, hi, zone string) Row {
	t.Helper()
	return Row{Lo: addr(t, lo), Hi: addr(t, hi), Zone: zone}
}

func TestZoneOfNeedsBothProvinceAndCarrier(t *testing.T) {
	cases := []struct {
		name   string
		record map[string]string
		want   string
	}{
		{"省+电信", map[string]string{"region_name": "广东省深圳", "isp_domain": "中国电信"}, "广东电信"},
		{"市名去掉市字", map[string]string{"region_name": "北京市", "isp_domain": "联通"}, "北京联通"},
		{"网通归一到联通", map[string]string{"region_name": "辽宁省", "isp_domain": "网通"}, "辽宁联通"},
		{"铁通归一到移动", map[string]string{"region_name": "江苏省", "owner_domain": "铁通"}, "江苏移动"},
		{"没有运营商就不打标", map[string]string{"region_name": "广东省", "isp_domain": "阿里云"}, ""},
		{"没有省份就不打标", map[string]string{"region_name": "香港", "isp_domain": "电信"}, ""},
		{"region 为空", map[string]string{"isp_domain": "电信"}, ""},
	}
	for _, tc := range cases {
		if got := ZoneOf(tc.record); got != tc.want {
			t.Errorf("%s: ZoneOf(%v) = %q，期望 %q", tc.name, tc.record, got, tc.want)
		}
	}
}

func TestMergeRowsJoinsAdjacentSameZone(t *testing.T) {
	merged, clipped := MergeRows([]Row{
		row(t, "1.0.1.0", "1.0.1.255", "广东电信"),
		row(t, "1.0.2.0", "1.0.2.255", "广东电信"),
		row(t, "1.0.4.0", "1.0.4.255", "广东电信"),
	})
	if clipped != 0 {
		t.Errorf("没有重叠时不该有裁剪，得到 %d", clipped)
	}
	if len(merged) != 2 {
		t.Fatalf("相邻同 zone 应当合并成 2 段，得到 %d: %+v", len(merged), merged)
	}
	if merged[0].Hi != addr(t, "1.0.2.255") {
		t.Errorf("首段应当延伸到 1.0.2.255，得到 %s", FormatAddr(merged[0].Hi))
	}
}

func TestMergeRowsKeepsDifferentZonesApart(t *testing.T) {
	merged, clipped := MergeRows([]Row{
		row(t, "1.0.1.0", "1.0.1.255", "广东电信"),
		row(t, "1.0.2.0", "1.0.2.255", "江苏联通"),
	})
	if clipped != 0 || len(merged) != 2 {
		t.Fatalf("不同 zone 不能合并，得到 %d 段 / 裁剪 %d", len(merged), clipped)
	}
}

func TestMergeRowsClipsCrossZoneOverlapKeepingTheEarlierStart(t *testing.T) {
	merged, clipped := MergeRows([]Row{
		row(t, "1.0.1.0", "1.0.1.255", "广东电信"),
		row(t, "1.0.1.128", "1.0.2.255", "江苏联通"),
	})
	if clipped != 1 {
		t.Errorf("跨 zone 重叠应当记一次裁剪，得到 %d", clipped)
	}
	if len(merged) != 2 {
		t.Fatalf("裁剪后仍应是两段，得到 %+v", merged)
	}
	if merged[1].Lo != addr(t, "1.0.2.0") {
		t.Errorf("后一段应当从 1.0.2.0 开始（起点更早的那条保留），得到 %s", FormatAddr(merged[1].Lo))
	}
	if _, bad := FirstOverlap(merged); bad {
		t.Error("裁剪之后不允许再有重叠")
	}
}

func TestMergeRowsDropsRowsFullyShadowed(t *testing.T) {
	merged, _ := MergeRows([]Row{
		row(t, "1.0.0.0", "1.0.3.255", "广东电信"),
		row(t, "1.0.1.0", "1.0.1.255", "江苏联通"),
	})
	if len(merged) != 1 {
		t.Fatalf("被完全遮蔽的一段应当丢弃，得到 %+v", merged)
	}
}

func TestFirstOverlapIsTheSelfCheckThatMustCatchBadOutput(t *testing.T) {
	if _, bad := FirstOverlap([]Row{
		row(t, "1.0.1.0", "1.0.1.255", "a"),
		row(t, "1.0.2.0", "1.0.2.255", "b"),
	}); bad {
		t.Error("不相交的行不该报重叠")
	}
	index, bad := FirstOverlap([]Row{
		row(t, "1.0.1.0", "1.0.2.255", "a"),
		row(t, "1.0.2.0", "1.0.3.255", "b"),
	})
	if !bad || index != 0 {
		t.Errorf("重叠必须被自检抓到，得到 index=%d bad=%v", index, bad)
	}
}

func TestDirectCoverageCountsAddressesNotEntries(t *testing.T) {
	direct := []ipset.Range{{Lo: addr(t, "1.0.0.0"), Hi: addr(t, "1.0.3.255")}}
	rows := []Row{row(t, "1.0.0.0", "1.0.1.255", "广东电信")}
	covered, total := DirectCoverage(rows, direct)
	if total != 1024 {
		t.Errorf("总地址数应为 1024，得到 %d", total)
	}
	if covered != 512 {
		t.Errorf("覆盖地址数应为 512，得到 %d", covered)
	}
}

func TestDirectCoverageClipsRowsOutsideDirect(t *testing.T) {
	direct := []ipset.Range{{Lo: addr(t, "1.0.1.0"), Hi: addr(t, "1.0.1.255")}}
	rows := []Row{row(t, "1.0.0.0", "1.0.3.255", "广东电信")}
	covered, total := DirectCoverage(rows, direct)
	if covered != 256 || total != 256 {
		t.Errorf("超出 direct4 的部分不该计入，得到 covered=%d total=%d", covered, total)
	}
}

func TestLoadDirectIntervalsSkipsCommentsAndBadLines(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "direct4.txt")
	body := "# 注释\n\n1.0.1.0/24\n垃圾\n2001:db8::/32\n223.5.5.0/24\n"
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("写夹具失败: %v", err)
	}
	ranges, err := LoadDirectIntervals(path)
	if err != nil {
		t.Fatalf("读取失败: %v", err)
	}
	if len(ranges) != 2 {
		t.Fatalf("只该收下两条 IPv4 网段，得到 %d: %+v", len(ranges), ranges)
	}
}

func TestRenderProducesTheFormatMosproxyParses(t *testing.T) {
	text := Render([]Row{row(t, "1.0.1.0", "1.0.1.255", "广东电信")})
	if !strings.HasPrefix(text, "# generated by dns-stack ecs-zone\n# format: start,end,zone\n") {
		t.Errorf("表头不对:\n%s", text)
	}
	if !strings.Contains(text, "1.0.1.0,1.0.1.255,广东电信\n") {
		t.Errorf("数据行格式不对:\n%s", text)
	}
}

func TestCountDataLinesIgnoresHeader(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "zone.txt")
	if err := os.WriteFile(path, []byte("# a\n# b\n1,2,x\n\n3,4,y\n"), 0o644); err != nil {
		t.Fatalf("写夹具失败: %v", err)
	}
	if got := CountDataLines(path); got != 2 {
		t.Errorf("只该数数据行，得到 %d", got)
	}
	if got := CountDataLines(filepath.Join(dir, "nope.txt")); got != 0 {
		t.Errorf("文件不存在应当返回 0，得到 %d", got)
	}
}
